version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Next.js Application
          command: npx next build
      - run:
          name: Run Cypress Tests
          command: npx cypress run --browser chrome

workflows:
  version: 2
  test:
    jobs:
      - build
